#############################################################################
# Makefile for building: gasblender
# Generated by qmake (2.01a) (Qt 4.8.6) on: sre. okt. 7 23:13:14 2015
# Project:  gasblender.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -o Makefile gasblender.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = costsdialog.cpp \
		gasblender.cpp \
		gerg2004.cpp \
		globalvar.cpp \
		main.cpp \
		qrc_gasblender.cpp moc_costsdialog.cpp \
		moc_gasblender.cpp
OBJECTS       = costsdialog.o \
		gasblender.o \
		gerg2004.o \
		globalvar.o \
		main.o \
		qrc_gasblender.o \
		moc_costsdialog.o \
		moc_gasblender.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		gasblender.pro
QMAKE_TARGET  = gasblender
DESTDIR       = 
TARGET        = gasblender

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_costsdialog.h ui_gasblender.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gasblender.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile gasblender.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile gasblender.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/gasblender1.0.0 || $(MKDIR) .tmp/gasblender1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/gasblender1.0.0/ && $(COPY_FILE) --parents costsdialog.h gasblender.h gerg2004.h globalvar.h .tmp/gasblender1.0.0/ && $(COPY_FILE) --parents costsdialog.cpp gasblender.cpp gerg2004.cpp globalvar.cpp main.cpp qrc_gasblender.cpp .tmp/gasblender1.0.0/ && $(COPY_FILE) --parents costsdialog.ui gasblender.ui .tmp/gasblender1.0.0/ && (cd `dirname .tmp/gasblender1.0.0` && $(TAR) gasblender1.0.0.tar gasblender1.0.0 && $(COMPRESS) gasblender1.0.0.tar) && $(MOVE) `dirname .tmp/gasblender1.0.0`/gasblender1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/gasblender1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_costsdialog.cpp moc_gasblender.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_costsdialog.cpp moc_gasblender.cpp
moc_costsdialog.cpp: ui_costsdialog.h \
		costsdialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) costsdialog.h -o moc_costsdialog.cpp

moc_gasblender.cpp: ui_gasblender.h \
		gasblender.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) gasblender.h -o moc_gasblender.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_costsdialog.h ui_gasblender.h
compiler_uic_clean:
	-$(DEL_FILE) ui_costsdialog.h ui_gasblender.h
ui_costsdialog.h: costsdialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic costsdialog.ui -o ui_costsdialog.h

ui_gasblender.h: gasblender.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic gasblender.ui -o ui_gasblender.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

costsdialog.o: costsdialog.cpp costsdialog.h \
		ui_costsdialog.h \
		gasblender.h \
		ui_gasblender.h \
		globalvar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o costsdialog.o costsdialog.cpp

gasblender.o: gasblender.cpp gasblender.h \
		ui_gasblender.h \
		costsdialog.h \
		ui_costsdialog.h \
		globalvar.h \
		gerg2004.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gasblender.o gasblender.cpp

gerg2004.o: gerg2004.cpp gerg2004.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gerg2004.o gerg2004.cpp

globalvar.o: globalvar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globalvar.o globalvar.cpp

main.o: main.cpp gasblender.h \
		ui_gasblender.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_gasblender.o: qrc_gasblender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_gasblender.o qrc_gasblender.cpp

moc_costsdialog.o: moc_costsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_costsdialog.o moc_costsdialog.cpp

moc_gasblender.o: moc_gasblender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gasblender.o moc_gasblender.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

